export interface QRPayload {
  v: 1;
  player: string;
  slips: string[];
}

export function encodePayload(playerName: string, slips: string[]): string {
  const payload: QRPayload = {
    v: 1,
    player: playerName.trim(),
    slips: slips.map(s => s.trim()),
  };
  return JSON.stringify(payload);
}

export function decodePayload(data: string): QRPayload | { error: string } {
  try {
    const parsed = JSON.parse(data);
    if (typeof parsed !== 'object' || parsed === null) {
      return { error: "Couldn't read that QR code. Make sure it was generated by this app." };
    }
    if (parsed.v !== 1) {
      return { error: 'This QR code is from a different version of the app.' };
    }
    if (!parsed.player || !Array.isArray(parsed.slips) || parsed.slips.length === 0) {
      return { error: 'That QR code seems incomplete. Try regenerating it.' };
    }
    return parsed as QRPayload;
  } catch {
    return { error: "Couldn't read that QR code. Make sure it was generated by this app." };
  }
}

export function generateJoinUrl(slipsPerPlayer: number): string {
  const origin = window.location.origin;
  const base = import.meta.env.BASE_URL || '/';
  return `${origin}${base}#/write?slips=${slipsPerPlayer}`;
}
